### ISSUE TITLE
[BUG] 'last_print_t' is preventing streamlit from reloading

### ISSUE THREAD

**Issue by rohitsathish** [Wirg/stqdm#98]
**Describe the bug**

```Exception ignored in: <function tqdm.__del__ at 0x000001CB35CCF880>
Traceback (most recent call last):
  File "C:\Users\rohit\anaconda3\envs\ws_st\lib\site-packages\tqdm\std.py", line 1149, in __del__
    self.close()
  File "C:\Users\rohit\anaconda3\envs\ws_st\lib\site-packages\stqdm\stqdm.py", line 109, in close
    super().close()
  File "C:\Users\rohit\anaconda3\envs\ws_st\lib\site-packages\tqdm\std.py", line 1278, in close
    if self.last_print_t < self.start_t + self.delay:       
AttributeError: 'stqdm' object has no attribute 'last_print_t'
```

**To Reproduce**

A simple app with two stqdm instances will produce the error upon a few reruns.

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Browser: Vivaldi
 - Version of streamlit : 1.33.0
 - Version of stqdm: 0.0.5
 - Version of tqdm: 4.66.1

**Comment by Wirg** [comment]
Hi @rohitsathish,

Thanks for reporting.

I was not able to reproduce with the following code.
It might be windows specific. In the past, I had some issues with Windows.
I don't have a windows machine currently but I could try again in a few weeks.

```python
from time import sleep
from stqdm import stqdm

for item in stqdm(range(10)):
    sleep(0.1)

for item in stqdm(range(10)):
    sleep(0.1)
```


Can you try to reproduce with the above code?
If it fails in the same way, can you try again with adding this on top of your file.

```python
from multiprocessing import RLock

from stqdm import stqdm
stqdm.set_lock(RLock())
```

**Comment by lachlan-centrifuge** [comment]
I have been experiencing this bug when running a job with hundreds of iterations, each lasting a couple of seconds.

To reproduce, all I had to do was use an input in the page above the stqdm object, which causes a rerun. This would break it without fail.

I have since refactored to use a vanilla streamlit progress bar, but I would prefer to get back to stqdm if we can fix it.

**Comment by Wirg** [comment]
This no longer reproduces in v0.2.0 with the current implementation and browser/demo test coverage.

I added a dedicated demo/test path around the rerun-style `last_print_t` issue. Closing this for now, but please reopen or comment with a fresh minimal reproduction if it still happens on v0.2.0.
